 SELECT ENAME , JOB 
   FROM EMP
   WHERE MGR IS NULL;


    SELECT GETDATE() AS 'DATE' ;

 SELECT e.ENAME , e.HIREDATE,m.ENAME,m.HIREDATE
   FROM EMP e,EMP m
   WHERE e.EMPNO = m.MGR AND e.HIREDATE < m.HIREDATE;

   SELECT COUNT(JOB) AS 'NO_OF_MANAGER'
   FROM EMP
   WHERE JOB = 'MANAGER';

   SELECT *
   FROM EMP
   WHERE DEPTNO IN (20,30,40);


   SELECT ENAME
   FROM EMP
   WHERE ENAME LIKE 'T%R';

   SELECT ENAME ,HIREDATE 
   FROM EMP
   WHERE DEPTNO = 30;

   SELECT *
   FROM EMP
   WHERE JOB = 'ANALYST' AND  HIREDATE='1984-12-03';


   SELECT TO_CHAR(hiredate,'DD.MM.YYYY:HH24:MI:SS') "hiredate"
  FROM emp;